server:
  port: 8080

spring:
  application:
    name: api-gateway

  # Where to fetch shared configs (overridden by config server)
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# OAuth2 resource-server: validate RS256 tokens using Auth Service JWKS
  security:
    jwt:
      public-key-location: classpath:keys/public.pem
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:9000/.well-known/jwks.json   # Auth Service JWKS
#          public-key-location: classpath:keys/public.pem

# Redis (rate limiter)

  redis:
    host: localhost
    port: 6379

# Resilience4j (defaults, can be overridden in config server)
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
    instances:
      accountCB:
        baseConfig: default
      customerCB:
        baseConfig: default
      transactionCB:
        baseConfig: default
      notificationCB:
        baseConfig: default

# Gateway routes (we use RouteLocator in code, discovery locator is enabled)

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie

# Tracing

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
