server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authentication-service/.well-known/jwks.json

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: customerServiceCB
                fallbackUri: forward:/fallback/customers
            - name: Resilience4jRateLimiter
              args:
                name: customerServiceRL

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: accountServiceCB
                fallbackUri: forward:/fallback/accounts
            - name: Resilience4jRateLimiter
              args:
                name: accountServiceRL

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: transactionServiceCB
                fallbackUri: forward:/fallback/transactions
            - name: Resilience4jRateLimiter
              args:
                name: transactionServiceRL

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: notificationServiceCB
                fallbackUri: forward:/fallback/notifications
            - name: Resilience4jRateLimiter
              args:
                name: notificationServiceRL

resilience4j:
  circuitbreaker:
    instances:
      customerServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      accountServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      transactionServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      notificationServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  ratelimiter:
    instances:
      customerServiceRL:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0
      accountServiceRL:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
      transactionServiceRL:
        limitForPeriod: 15
        limitRefreshPeriod: 1s
        timeoutDuration: 0
      notificationServiceRL:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 0
