server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: account-route
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@principalNameKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: accountServiceCircuit
                fallbackUri: forward:/fallback/account
            - name: JwtForwardingFilter

        - id: customer-route
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: customerServiceCircuit
                fallbackUri: forward:/fallback/customer
            - name: JwtForwardingFilter

        - id: transaction-route
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: CircuitBreaker
              args:
                name: transactionServiceCircuit
                fallbackUri: forward:/fallback/transaction
            - name: JwtForwardingFilter

        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuit
                fallbackUri: forward:/fallback/notification
            - name: JwtForwardingFilter

    config:
      uri: http://localhost:8888   # Spring Cloud Config server

  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
