server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # Enable service discovery (Eureka/Consul)
          lower-case-service-id: true
      routes:
        # Customer Service Route
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**   # Example: /customers/123
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: customerServiceCB
                fallbackUri: forward:/fallback/customers

        # Account Service Route
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: accountServiceCB
                fallbackUri: forward:/fallback/accounts

        # Transaction Service Route
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: transactionServiceCB
                fallbackUri: forward:/fallback/transactions

        # Notification Service Route
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - JwtForwardingFilter
            - name: CircuitBreaker
              args:
                name: notificationServiceCB
                fallbackUri: forward:/fallback/notifications

    # Resilience4j (Circuit Breaker + Rate Limiting)
resilience4j:
  circuitbreaker:
    instances:
      customerServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      accountServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      transactionServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      notificationServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  ratelimiter:
    instances:
      default:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 0

# Logging (structured logs with traceId/spanId)
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    com.example.gateway: DEBUG

# Distributed tracing (Sleuth + Zipkin)

  sleuth:
    sampler:
      probability: 1.0   # Trace 100% requests
  zipkin:
    base-url: http://localhost:9411   # Zipkin server

# Eureka client (if using Eureka)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
