server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  access-token-exp-ms: 900000      # 15 minutes
  refresh-token-exp-ms: 1209600000 # 14 days
  private-key-pem: classpath:keys/rsa_private.pem
  public-key-pem: classpath:keys/rsa_public.pem
  issuer: auth.mybank.local

