server:
  port: 8084   # Notification Service runs on different port

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com   # Gmail SMTP server
    port: 587              # Port for TLS
    username: "mybank.notificationsender@gmail.com"
    password: "nxjn ciuo wxdu zxtg"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"



